#!/bin/bash
DIR="$(dirname "$(readlink -f "$0")")"
ME="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"
if [ ! -f /.dockerenv ]; then
    $DIR/execute_in_docker $DIR/$ME $@
    exit $?
fi

if [ "$#" -eq 0 ]; then
    COMPILER=gcc
    BUILD=debug
elif  [ "$#" == 2 ]; then 
    COMPILER=$1
    BUILD=$2
else
    echo "build <compiler> <build_type> | doc"
    exit 1
fi
    
touch $DIR/../CMakeLists.txt
(cd `readlink -f $DIR/../build`/${COMPILER=}_${BUILD} && ninja)



