#!/bin/bash
DIR="$(dirname "$(readlink -f "$0")")"
SRC_ROOT=$DIR/..
CMD=$@
source $DIR/../cppbs/project_settings

if [[ $DIR != *"jenkins"* ]]; then
	I="-i"
fi

read -d '' docker_cmd << EOF
docker run \
      --rm \
      --net host \
      -h $(hostname)_cpp \
      -e "TZ=America/New_York" \
      --security-opt seccomp=unconfined \
      -v /var/log/syslog:/var/log/syslog \
      -v /usr/local/share/fonts:/usr/local/share/fonts \
      -v /usr/share/fonts:/usr/share/fonts \
      -v /run/user/:/run/user/ \
      -v /tmp:/tmp \
      -v /etc/group:/etc/group \
      -v /etc/passwd:/etc/passwd \
      -v /tmp:/tmp \
      -v /etc/sudoers:/etc/sudoers \
      -v /home:/home \
      --shm-size=4024m \
      -w $SRC_ROOT \
      -u $UID \
      -t \
      $I -e DISPLAY=$DISPLAY \
    $PROJECT_NAME 
EOF

if [ -f /.dockerenv ]; then
    $CMD
else
    echo "Running $CMD"
    $docker_cmd $CMD
fi
