#!/bin/bash
DIR="$(dirname "$(readlink -f "$0")")"
SRC_ROOT=$DIR/..
CMD=$@
source $DIR/../cppbs/project_settings

read -d '' podman_cmd << EOF
podman run \
      --rm \
      --net host \
      --userns=keep-id \
      -h $(hostname)_podman \
      -e "TZ=America/New_York" \
      --security-opt seccomp=unconfined \
      --privileged \
      -v /var:/var \
      -v /run/user/:/run/user/ \
      -v /tmp:/tmp \
      -v /home:/home \
      --shm-size=4024m \
      -w $SRC_ROOT \
      -t \
      -e DISPLAY=$DISPLAY \
    $PROJECT_NAME 
EOF

if [ "$container" = "podman" ]; then 
    $CMD
else 
    $podman_cmd $CMD
fi

