#!/bin/bash

DIR="$(dirname "$(readlink -f "$0")")"
source $DIR/../cppbs/project_settings

podman run \
      --rm \
      --net host \
      --userns=keep-id \
      -h $(hostname)_cppbs\
      -e "TZ=America/New_York" \
      --security-opt seccomp=unconfined \
      --privileged \
      -v /var:/var \
      -v /tmp:/tmp \
      -v /home:/home \
      --shm-size=4024m \
      -it \
      -e DISPLAY=$DISPLAY \
      $PROJECT_NAME \
      /bin/bash 
