#!/bin/bash
DIR="$(dirname "$(readlink -f "$0")")"
ME="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"
if [ ! -f /.dockerenv ]; then
    $DIR/execute_in_docker $DIR/$ME $@
    exit $?
fi


$DIR/build gcc debug &&
    (cd $DIR/../build/gcc_debug/bin && ./$@)
